spring:
  datasource:
    url: jdbc:mysql://localhost:3306/message?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: localhost
    port: 6379
    database: 1
server:
  servlet:
    context-path: /message
logging:
  config: classpath:log4j2.xml